version: "3.8"
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: monitoring_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    
  prometheus:
    image: promwithconfig
    build: 
      context: prometheus
    container_name: monitoring_prometheus
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
      - GF_USERS_ALLOW_SIGN_UP=false

  jaeger:
    image: jaegertracing/all-in-one:1.47
    container_name: jaeger
    restart: unless-stopped
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp 
      - 6832:6832/udp 
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
  example-hotrod:
    image: jaegertracing/example-hotrod:1.47
    container_name: example-hotrod
    environment:
      - JAEGER_AGENT_HOST=jaeger
    ports:
      - 8080-8083:8080-8083
    command: all
    depends_on:
      - jaeger

  nats:
    image: natswithconfig
    build: 
      context: nats
    container_name: nats-server
    restart: unless-stopped
    expose:
      - 4222
      - 8222
      - 6222
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222

volumes:
  grafana_data: